window.tailwind = window.tailwind || {};

window.tailwind.config = {
  darkMode: 'class',
  safelist: [
    'bg-surface',
    'sticky',
    'top-0',
    'z-50',
    'border-b',
    'border-outline-variant',
    'flex',
    'justify-between',
    'items-center',
    'h-16',
    'w-full',
    'max-w-container-max',
    'mx-auto',
    'px-gutter',
    'gap-xl',
    'hidden',
    'md:flex',
    'gap-lg',
    'h-full',
    'font-display',
    'font-body-md',
    'text-h2',
    'text-body-md',
    'font-bold',
    'font-medium',
    'text-primary',
    'text-secondary',
    'text-on-primary',
    'tracking-tight',
    'px-md',
    'py-sm',
    'bg-primary',
    'rounded-lg',
    'hover:bg-primary-container',
    'hover:text-primary',
    'active:scale-95',
    'transition-all',
    'transition-colors'
  ],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dcd9d9',
        'primary-container': '#0070eb',
        primary: '#0058bc',
        'on-tertiary-fixed': '#07006c',
        'outline-variant': '#c1c6d7',
        error: '#ba1a1a',
        secondary: '#5e5e5e',
        'inverse-primary': '#adc6ff',
        'on-surface-variant': '#414755',
        'on-secondary-fixed-variant': '#474747',
        'on-primary': '#ffffff',
        'tertiary-container': '#6063ee',
        tertiary: '#4648d4',
        'on-secondary-container': '#646464',
        surface: '#fcf9f8',
        'secondary-fixed-dim': '#c6c6c6',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#1b1b1b',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#c0c1ff',
        'on-tertiary-container': '#fffbff',
        'on-surface': '#1c1b1b',
        'surface-variant': '#e5e2e1',
        'secondary-fixed': '#e2e2e2',
        'on-primary-fixed': '#001a41',
        'surface-container-high': '#ebe7e7',
        'on-background': '#1c1b1b',
        'secondary-container': '#e2e2e2',
        'inverse-on-surface': '#f3f0ef',
        'on-primary-fixed-variant': '#004493',
        'on-primary-container': '#fefcff',
        'surface-container-low': '#f6f3f2',
        'surface-tint': '#005bc1',
        'inverse-surface': '#313030',
        'surface-container-highest': '#e5e2e1',
        'surface-bright': '#fcf9f8',
        'primary-fixed': '#d8e2ff',
        'on-secondary': '#ffffff',
        outline: '#717786',
        'primary-fixed-dim': '#adc6ff',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#2f2ebe',
        background: '#fcf9f8',
        'surface-container': '#f0edec',
        'tertiary-fixed': '#e1e0ff'
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem'
      },
      spacing: {
        base: '4px',
        sm: '8px',
        md: '16px',
        'container-max': '1280px',
        lg: '24px',
        xl: '48px',
        xs: '4px',
        gutter: '20px'
      },
      maxWidth: {
        'container-max': '1280px'
      },
      fontFamily: {
        'code-md': ['JetBrains Mono'],
        'body-sm': ['Space Grotesk'],
        'body-md': ['Space Grotesk'],
        h1: ['Space Grotesk'],
        h2: ['Space Grotesk'],
        display: ['Space Grotesk'],
        'body-lg': ['Space Grotesk'],
        'label-md': ['Space Grotesk'],
        h3: ['Space Grotesk']
      },
      fontSize: {
        'code-md': ['14px', { lineHeight: '1.7', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.4', fontWeight: '600' }]
      }
    }
  }
};
